import type { Metadata } from "next";
import { Fraunces, Montserrat } from "next/font/google";
import "./globals.css";

const fraunces = Fraunces({
  subsets: ["latin"],
  weight: "700",
  variable: "--font-fraunces"
});
const mont = Montserrat({
  subsets: ["latin"],
  weight: ["500", "700"],
  variable: "--font-mont"
});

export const metadata: Metadata = {
  title: "Product Preview Card",
  description: "Generated by PhDBui"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={`${fraunces.variable} ${mont.variable}`}>
        {children}
      </body>
    </html>
  );
}
